name: ci 
on:
  push:
    branches:
      - main 
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Load Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
          
      - name: Show cache info
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      
      - name: Setup cache
        uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
            
      - name: Load MKDocs Material
        run: pip install mkdocs-material 
      
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force

      - name: Deploy to Digital Ocean droplet
        uses: wlixcc/SFTP-Deploy-Action@v1.2.5
        with:
          username: 'sftpuser'
          server: '209.38.60.133'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './'
          remote_path: '~/html'
          rsyncArgs: '--exclude=.git --exclude=*.log'
          sftpArgs: '-o ConnectTimeout=5'
