name: CI/CD
on:
  push:
    branches: [main]
    tags: ['v[0-9].[0-9]+.[0-9]+']
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4    
      - name: Load Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Setup cache
        uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: mkdocs-material-
      - name: Load MKDocs Material
        run: pip install mkdocs-material 
      - name: Build site
        run: mkdocs build
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
      - name: Deploy to Digital Ocean droplet
        uses: wlixcc/SFTP-Deploy-Action@v1.2.5
        if: ${{ ! startsWith(github.ref, 'refs/tags/v') }}
        with:
          username: 'sftpuser'
          server: '209.38.60.133'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './site/*'
          remote_path: 'html'
          sftp_only: true
          sftpArgs: '-o ConnectTimeout=5'
